---
title: "Impactos directos observados en Puerto Humo "
---
\
\
\
<p align="justify">
Puerto Humo se ubicada a 28 kilómetros al noroeste de la ciudad colonial de Nicoya, en sus primeros años el desarrollo de esta comunidad se basó en la Comercialización de madera que era transportada hacia Puntarenas y posterior mente la introducción de ganado. 
</p>
<p align="justify">
Para el año 2012 se forma una Asociación de Desarrollo y a partir de ahí se empieza  a desarrollar proyectos para la comunidad. Para el año 2018 un grupo de vecinos y la asociación de Puerto Humo unen fuerzas con el SINAC para lograr vínculos y lograr acercar el turismo tanto nacional como extranjero a la zona ya que es un lugar importante para la observación de aves 
</p>
\
\


Puerto Humo|0  | 1 | 2   | 3 | 4 | 5  
-----------|---|---|-----|---|---|----
Residuos sólidos| |x | | | |
Vertido de Hidrocarburos|x | | | | |
Basura en General||x | | | |
Aguas residuales| |x | | | |
Tala| | |x | | |
***

0. No hay evidencia presente
1. Hay una leve sospecha
2. La afectación y contenido es leve
3. La afectación es moderada en los
alrededores
4. La afectación es fuerte y evidente
5. La afectación es grave (hay descontrol
\
\
\
<p align="justify">
En la localidad de Puerto Humo se observo una tala moderada de la zona, seguramente debido a que históricamente la extracción de madera fue una de las principales  actividades económicas,  no se observaron contaminación de hidrocarburos o residuos sólidos sin embargo, por el tipo de actividad de la zona se sospecha que haya algun tipo de afectacion por residuos solidos.
</p>
